services:
  postgres:
    container_name: autre-tunisie-postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ../../data:/var/lib/postgresql/data
      - ../../init:/docker-entrypoint-initdb.d
    networks:
      - default

  redis:
    container_name: autre-tunisie-redis
    image: redis:latest
    ports:
        - "6379:6379"
    networks:
        - default

networks:
    default:
        name: test-network
        external: true